name: dotnet build

on:
  push:
    branches: [ main, live ]
  pull_request:
    branches: [ main, live ]

permissions:
  contents: read

jobs:
  build:
    defaults:
      run:
        working-directory: src/
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
